### ISSUE TITLE
The swipe button is not working when using Right to Left reading languages

### ISSUE THREAD

**Issue by suryamin** [lrferreiro/flutter_swipe_button#8]
Hi,

Thank you for this great flutter_swipe_button package.
It was working great until I added a Right to Left reading language support to my application, like Arabic, Hebrew, etc. The swipe button is not working anymore, the position of the button is on the right and can not be swiped.

Are you able to add a locale property to enable those Right to Left reading languages feature?
This is pretty much not a bug but just asking for a new feature which is locale support.

Thank you.

Kind regards,
Surya

**Comment by lrferreiro** [comment]
Hi,
When you use another language like these where the writing is from right to left, the button already has the behavior built in. I suggest you update the version, because when the Locale changes, the TextDirection of the context must change. These are the lines that are already built in, which check this value to give it the correct behavior.

```
final TextDirection currentDirection = Directionality.of(context);
final bool isRTL = currentDirection == TextDirection.rtl;
```
